### ISSUE TITLE
Prefilled data gets cleared on leave

### ISSUE THREAD

**Issue by hunter-koppen** [bizzomate/bizzomateNumberInput#1]
Hi, I like the widget but it seems to contain a bug. I have a popup with the widget on it which shows a value in euros. If I first create an object and set a default value then opening the poup and clicking inside the input and then outside it, it will clear the data.

**Comment by valczak** [comment]
I discovered exactly the same thing a while ago and came here to report it, but you beat me to it ;) 
This is more of a bug in the critical category because it renders the widget useless

**Comment by JelleDekker** [comment]
Thanks for reporting, will look into it. Can you share some extra details? Are you using Integer, Decimal or String (or does it always happen)? Also which Mx version?

**Comment by valczak** [comment]
I tried this only with decimal numbers. When the user clicks on the field and leaves it unchanged, the value disappears (it's not 0, it's empty).

Mendix 10.4, Java 21

**Comment by JelleDekker** [comment]
Release 1.0.1 should fix this and has just been released to the Mendix Marketplace. Again, thanks for reporting!

**Comment by valczak** [comment]
No, and still the problem persists. But only when the value at the beginning is 0

**Comment by JelleDekker** [comment]
> No, and still the problem persists. But only when the value at the beginning is 0

Aah yes, for decimal input the "0" was treated as undefined. Fixed in 1.1.0, see update in the Marketplace. Thanks again!
